### ISSUE TITLE
lib crate depends on clap

### ISSUE THREAD

**Issue by oconnor663** [WanzenBug/xch#1]
Clap is a pretty big dependency, and it's only needed in main.rs (not lib.rs or anything under it). I'd like to take a library dependency on this crate, but I don't want to make my crate depend on clap. Would it be possible to split the binary off into its own crate, so that the dependencies could be separated? (As in https://github.com/oconnor663/blake2_simd/tree/master/blake2_bin.)

**Comment by WanzenBug** [comment]
Sure. 

Since there are literally only 3 arguments to parse I will probably just replace clap entirely.

**Comment by WanzenBug** [comment]
Just finished refactoring a lot of internals.

I removed `clap` as well as `cfg_if` and updated some older dependencies to newer version. The binary itself now does not need any additional dependencies, so I think this issue can be considered closed

**Comment by oconnor663** [comment]
Thanks for the quick turnaround!
